config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'
  get "about" => "home#about"
  resources :home
  
  devise_for :users, controllers: { registrations: "registrations" }

  resources :leaves

  get    'admin'   => 'rails_admin/main#dashboard'
  get    'back'    => 'rails_admin/main#show_in_app'

end

app/models/leave.rb
class Leave < ActiveRecord::Base
	belongs_to :user

	validates :from_date,  presence: true
	validates :to_date,  presence: true
    validates_numericality_of :no_of_days, 
                          :greater_than_or_equal_to =>0, 
                          :message => "To_date must be greater than from_date"

	validates :type_of_leave,  presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :firstname,  presence: true, length: { maximum: 20 }
  validates :lastname,  presence: true, length: { maximum: 20 }
  validates :date_of_joining,  presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :leaves  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    if user_signed_in?
       if current_user.aproval == true
      
      redirect_to leaves_path(current_user)
       else
        redirect_to home_path(current_user)
       end
    end
  end

  def new

  end

  def create
  end

  def show

  end

  def update
  end

  def delete
  end

  def about
  end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  
before_action :authenticate_user!
  def index
  gon.date = current_user.date_of_joining
  @leaves = Leave.all

  end
  
  def new
    @leave = current_user.leaves.build
  end

  def show
     @leave = Leave.find(params[:id])
  end

  def create
     @leave = current_user.leaves.build(user_params) 
     if @leave.save
       redirect_to leave_path(@leave)
     else
       render 'new'
     end
  end

  def update
  end

  def destroy
  end

  
private
    def user_params
     params.require(:leave).permit(:from_date, :to_date, :reason, :type_of_leave, :no_of_days )                                       
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 def index
 
 end
 private
  def sign_up_params
  	params.require(:user).permit(:firstname, :lastname, :date_of_joining, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :date_of_joining, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leave_helper.rb
module LeaveHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/home/about.html.erb
<div class="container-fluid bg-1 text-center">
  
  
 <h1>Welcome to about page...!!!</h1>	
  
</div>

app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

app/views/home/delete.html.erb
<h1>Home#delete</h1>
<p>Find me in app/views/home/delete.html.erb</p>

app/views/home/index.html.erb
<div class="container-fluid bg-1 text-center">
  <div class="col-sm-3">  
  <%= image_tag ("logo.png") %>
  <h3>Universum Global</h3>
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary", id: "sign" %>
  </div>
</div>

<script type="text/javascript">
  $(function() {    
    $( "#datepicker" ).datepicker();  
   }); 
</script>

app/views/home/new.html.erb
<h1>Home#new</h1>
<p>Find me in app/views/home/new.html.erb</p>

app/views/home/show.html.erb
<div class="container">
<h1>Welcome to Leave Management</h1>
<h1>Your Aproval is stil pending !</h1>
</div>

app/views/home/update.html.erb
<h1>Home#update</h1>
<p>Find me in app/views/home/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container-fluid bg-4 text-center">
  <a href="http://universumglobal.com/">Univeresum Software India pvt ltd</a>
</footer>

app/views/layouts/_header.html.erb
<header>  
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand">Leave Management System</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path  %></li>
          <% if user_signed_in? %>
          <%if current_user.admin == true %>
          <li><%= link_to "Admin page", admin_path %></li>
          <% end %>
          <li><%= link_to "Log out", destroy_user_session_path, :method => "delete" %></li>
          <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
      </ul>
        
    </div>
  </div>
</nav> 
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeaveManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= include_gon %>
</head>
<body>
<%= render 'layouts/header' %>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/leaves/_error_message.html.erb
<% if object.errors.any? %>
  
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@leave.errors.count, "error") %>.
    </div>
    <ul>
    <% @leave.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>

<% end %>

app/views/leaves/destroy.html.erb
<h1>Leaves#destroy</h1>
<p>Find me in app/views/leaves/destroy.html.erb</p>

app/views/leaves/index.html.erb
<div class="container">
	<h1><%= current_user.firstname %></h1>
     <% if (current_user.leaves.count >= 1) %>
	<table border='1'>
  <tr>  
    <th>From Date</th>
    <th>To Date</th>
    <th>No of Days</th>
    <th>Type of Leave</th>
    <th>Reason</th>
  </tr>
	<% current_user.leaves.each do |leave| %> 
 <tr><td><%= leave.from_date.strftime("%d-%m-%Y") %></td>
	<td><%= leave.to_date.strftime("%d-%m-%y") %></td>
	<td><%= leave.no_of_days %></td>
	<td><%= leave.type_of_leave %></td>
	<td><%= leave.reason %></td></tr>
<% end %>
</table>
<br/>
<% end %>
<%= link_to 'Apply Leave', new_leave_path %>
</div>

app/views/leaves/new.html.erb
<h1>Leave Form</h1>
<div class="row">
	<div class="col-md-5 ">
	</div>
  	<div class="col-md-7 ">
		<%= form_for @leave do |f| %>
		<%= render 'leaves/error_message', object: f.object %>
			<%= f.label :from_date %>
			<%= f.text_field :from_date, class: 'datepicker', id: 'first' %><br />
		    <%= f.label :to_date %>
		    <%= f.text_field :to_date, class: 'datepicker', id: 'second'%>
		    <br/>
		    <%= f.label :no_of_days %>
		    <%= f.text_field :no_of_days,  id: 'btn'%> 
		    <%= content_tag :div do  %>
		     	<%= f.label :type_of_leave %>
		      	<%= f.select :type_of_leave, ["Sick Leave", "Planned Leave" ,"Casual Leave"],:prompt=>"select", id: "dropdown" %>
	      	<% end %>
	        <%= f.label :reason %>
		    <%= f.text_area :reason %><br />
		    <%= f.submit "Apply", class: "btn btn-primary", id:"sign" %>
		<% end %>
   	<%= link_to 'Applied Leave', leaves_path, class: "link" %>
	</div>
</div>

<script type="text/javascript">
$(document).ready( function() {
  $('.datepicker').datepicker({ dateFormat: 'dd-mm-yy' });


$("#btn").mouseenter(function(){
	var a = $('#first').val();
  var b = $('#second').val();
  var c = a.split('-')
  var d = b.split('-')
  var e = (d[0]-c[0])+1

	$("#btn").val(e);
}); 

});
</script>

app/views/leaves/show.html.erb
   
<div class= "container">
   <h1><%= @leave.user.firstname %></h1>
	<ul >
		<li>From:<%= @leave.from_date.strftime("%d-%m-%Y") %></li><br>
		<li>To:<%= @leave.to_date.strftime("%d-%m-%Y") %></li><br>
		<li>Type of Leave:<%= @leave.type_of_leave %></li><br>
		<li>Reason:<%= @leave.reason %></li><br>
		<li>No Of Days:<%= @leave.no_of_days %></li><br>
	</ul>
	<% if (current_user.firstname == @leave.user.firstname) %>
    <%= link_to 'Applied Leave', leaves_path %>
    <% end %>
</div>

app/views/leaves/update.html.erb
<h1>Leaves#update</h1>
<p>Find me in app/views/leaves/update.html.erb</p>
<% if (current_user.firstname == leave.user.firstname) %>